version: 0.2

phases:
  install:
    commands:
      - wget https://github.com/SonarSource/sonar-scanner-msbuild/releases/download/4.7.1.2311/sonar-scanner-msbuild-4.7.1.2311-netcoreapp2.0.zip
      - unzip sonar-scanner-msbuild-4.7.1.2311-netcoreapp2.0.zip
      - ls
      - ls ./sonar-scanner-msbuild-4.7.1.2311-netcoreapp2.0/*
